<?php

namespace App\Http\Requests\Administracion;

use Illuminate\Foundation\Http\FormRequest;

class ClienteRequest extends FormRequest {
    
    public function authorize() {
        return true;
    } 

    public function rules() {
        return [ 
            'CLIE_NOMBRE' => 'required|string|max:50', 
            'CLIE_NOMBRE2' => 'required|string|max:50', 
            'CLIE_NOMBRE3' => 'nullable|string|max:50', 
            'CLIE_APELLIDO' => 'required|string|max:50', 
            'CLIE_APELLIDO2'=> 'required|string|max:50',
            'CLIE_APELLIDO3' => 'nullable|string|max:50',
            'CLIE_SEXO' => 'required|string|max:1',
            'ESTA_ID' => 'required|string|max:10', 
            'PAIS_NAC' => 'required|string|max:10',
            'DEPA_NAC' => 'required|string|max:10', 
            'CLIE_FECHANAC' => 'required|date',
            'CLIE_DOCIDEN' => 'required|string|max:20', 
            'CLIE_DOCIDENVEN' => 'required|date',
            'CLIE_DOCFISCAL' => 'nullable|string|max:20',
            'CLIE_PASAPORTE' => 'nullable|string|max:20',
            'CLIE_OTRODOC' => 'nullable|string|max:20',
            'CLIE_OTRODOC2' => 'nullable|string|max:20',
            'CLIE_ANTECEDENTES' => 'required|integer|max:20',
            'PAIS_ID' => 'nullable|string|max:3',
            'DEPA_ID' => 'nullable|string|max:3',
            'MUNI_ID' => 'required|string|max:10',
            'CLIE_DIRECCION' => 'required|string|max:100',
            'CLIE_TEL' => 'required|string|max:20',
            'CLIE_TEL2' => 'nullable|string|max:20',
            'CLIE_MAIL' => 'required|string|max:50',
            'CLIE_MAIL2' => 'nullable|string|max:50',
            'CLIE_TIPOCASA' => 'required|integer|max:1',
            'CLIE_PROFESION' => 'required|string|max:50',
            'CLIE_TIPOEMPLEO' => 'required|integer|max:1',
            'CLIE_TRABAJO' => 'required|string|max:50',
            'CLIE_TRABAJODIR' => 'required|string|max:100',
            'CLIE_TRABAJOTEL' => 'required|string|max:20',
            'CLIE_INGRESOPROM' => 'required|numeric',
            'CLIE_INGRESOS' => 'required|numeric',
            'CLIE_INGRESOADIC' => 'required|boolean',
            'CLIE_INGRESOORIGEN' => 'required|string|max:50',
            'CLIE_REF1NOMBRE' => 'nullable|string|max:50',
            'CLIE_REF1PARENTESCO' => 'nullable|string|max:50',
            'CLIE_REF1DIRECCION' => 'nullable',
            'CLIE_REF1TELEFONO' => 'nullable',
            'CLIE_REF2NOMBRE' => 'nullable',
            'CLIE_REF2PARENTESCO' => 'nullable',
            'CLIE_REF2DIRECCION' => 'nullable',
            'CLIE_REF2TELEFONO' => 'nullable',
            'CLIE_REF3NOMBRE' => 'nullable',
            'CLIE_REF3PARENTESCO' => 'nullable',
            'CLIE_REF3DIRECCION' => 'nullable',
            'CLIE_REF3TELEFONO' => 'nullable',
            'CLIE_COMENTARIOS' => 'nullable',
            'CLIE_OBSERVACIONES' => 'nullable',
            'CLIE_TIPOCLIENTE' => 'required|integer|max:1',
            'CLIE_CATEGORIA' => 'required|string',
            'CLIE_SCORE' => 'required|numeric',
            'CLIE_ESTADO' => 'nullable|string|max:1',
            'SUCU_ID' => 'required|string|max:10',
            'EMPR_ID' => 'nullable',
            'USUA_LOGIN' => 'nullable',
            'FECHA_CAMBIO' => 'nullable|date',
        ];
    }

    public function messages() {
        return [
            'CLIE_NOMBRE.required' => 'El campo CLIE_NOMBRE es requerido',
            'CLIE_NOMBRE.string' => 'El campo CLIE_NOMBRE debe ser de tipo string',
            'CLIE_NOMBRE.max' => 'El campo CLIE_NOMBRE no debe exceder de 50 caracteres',
            'CLIE_NOMBRE2.required' => 'El campo CLIE_NOMBRE2 es requerido',
            'CLIE_NOMBRE2.string' => 'El campo CLIE_NOMBRE2 debe ser de tipo string',
            'CLIE_NOMBRE2.max' => 'El campo CLIE_NOMBRE2 no debe exceder de 50 caracteres',
            'CLIE_NOMBRE3.required' => 'El campo CLIE_NOMBRE3 es requerido',
            'CLIE_NOMBRE3.string' => 'El campo CLIE_NOMBRE3 debe ser de tipo string',
            'CLIE_NOMBRE3.max' => 'El campo CLIE_NOMBRE3 no debe exceder de 50 caracteres',
            'CLIE_APELLIDO.required' => 'El campo CLIE_APELLIDO es requerido',
            'CLIE_APELLIDO.string' => 'El campo CLIE_APELLIDO debe ser de tipo string',
            'CLIE_APELLIDO.max' => 'El campo CLIE_APELLIDO no debe exceder de 50 caracteres',
            'CLIE_APELLIDO2.required' => 'El campo CLIE_APELLIDO2 es requerido',
            'CLIE_APELLIDO2.string' => 'El campo CLIE_APELLIDO2 debe ser de tipo string',
            'CLIE_APELLIDO2.max' => 'El campo CLIE_APELLIDO2 no debe exceder de 50 caracteres',
            'CLIE_APELLIDO3.required' => 'El campo CLIE_APELLIDO3 es requerido',
            'CLIE_APELLIDO3.string' => 'El campo CLIE_APELLIDO3 debe ser de tipo string',
            'CLIE_APELLIDO3.max' => 'El campo CLIE_APELLIDO3 no debe exceder de 50 caracteres',
            'CLIE_SEXO.required' => 'El campo CLIE_SEXO es requerido',
            'CLIE_SEXO.string' => 'El campo CLIE_SEXO debe ser de tipo string', 
            'CLIE_SEXO.max' => 'El campo CLIE_SEXO no debe exceder de 1 caracter',
            'ESTA_ID.required' => 'El campo ESTA_ID es requerido',
            'ESTA_ID.string' => 'El campo ESTA_ID debe ser de tipo string',
            'ESTA_ID.max' => 'El campo ESTA_ID no debe exceder de 1 caracter',
            'PAIS_NAC.required' => 'El campo PAIS_NAC es requerido',
            'PAIS_NAC.string' => 'El campo PAIS_NAC debe ser de tipo string',
            'PAIS_NAC.max' => 'El campo PAIS_NAC no debe exceder de 3 caracteres',
            'DEPA_NAC.required' => 'El campo DEPA_NAC es requerido',
            'DEPA_NAC.string' => 'El campo DEPA_NAC debe ser de tipo string',
            'DEPA_NAC.max' => 'El campo DEPA_NAC no debe exceder de 3 caracteres',
            'CLIE_FECHANAC.required' => 'El campo CLIE_FECHANAC es requerido',
            'CLIE_FECHANAC.date' => 'El campo CLIE_FECHANAC debe ser de tipo date',
            'CLIE_DOCIDEN.required' => 'El campo CLIE_DOCIDEN es requerido',
            'CLIE_DOCIDEN.string' => 'El campo CLIE_DOCIDEN debe ser de tipo string',
            'CLIE_DOCIDEN.max' => 'El campo CLIE_DOCIDEN no debe exceder de 20 caracteres',
            'CLIE_DOCIDENVEN.required' => 'El campo CLIE_DOCIDENVEN es requerido',
            'CLIE_DOCIDENVEN.date' => 'El campo CLIE_DOCIDENVEN debe ser de tipo date',
            'CLIE_DOCFISCAL.required' => 'El campo CLIE_DOCFISCAL es requerido',
            'CLIE_DOCFISCAL.string' => 'El campo CLIE_DOCFISCAL debe ser de tipo string',
            'CLIE_DOCFISCAL.max' => 'El campo CLIE_DOCFISCAL no debe exceder de 20 caracteres',
            'CLIE_PASAPORTE.required' => 'El campo CLIE_PASAPORTE es requerido',
            'CLIE_PASAPORTE.string' => 'El campo CLIE_PASAPORTE debe ser de tipo string',
            'CLIE_PASAPORTE.max' => 'El campo CLIE_PASAPORTE no debe exceder de 20 caracteres',
            'CLIE_OTRODOC.required' => 'El campo CLIE_OTRODOC es requerido',
            'CLIE_OTRODOC.string' => 'El campo CLIE_OTRODOC debe ser de tipo string',
            'CLIE_OTRODOC.max' => 'El campo CLIE_OTRODOC no debe exceder de 20 caracteres',
            'CLIE_OTRODOC2.required' => 'El campo CLIE_OTRODOC2 es requerido',
            'CLIE_OTRODOC2.string' => 'El campo CLIE_OTRODOC2 debe ser de tipo string',
            'CLIE_OTRODOC2.max' => 'El campo CLIE_OTRODOC2 no debe exceder de 20 caracteres',
            'CLIE_ANTECEDENTES.required' => 'El campo CLIE_ANTECEDENTES es requerido',
            'CLIE_ANTECEDENTES.string' => 'El campo CLIE_ANTECEDENTES debe ser de tipo string',
            'CLIE_ANTECEDENTES.max' => 'El campo CLIE_ANTECEDENTES no debe exceder de 20 caracteres',
            'PAIS_ID.required' => 'El campo PAIS_ID es requerido',
            'PAIS_ID.string' => 'El campo PAIS_ID debe ser de tipo string',
            'PAIS_ID.max' => 'El campo PAIS_ID no debe exceder de 3 caracteres',
            'DEPA_ID.required' => 'El campo DEPA_ID es requerido',
            'DEPA_ID.string' => 'El campo DEPA_ID debe ser de tipo string',
            'DEPA_ID.max' => 'El campo DEPA_ID no debe exceder de 3 caracteres',
            'MUNI_ID.required' => 'El campo MUNI_ID es requerido',
            'MUNI_ID.string' => 'El campo MUNI_ID debe ser de tipo string',
            'MUNI_ID.max' => 'El campo MUNI_ID no debe exceder de 3 caracteres',
            'CLIE_DIRECCION.required' => 'El campo CLIE_DIRECCION es requerido',
            'CLIE_DIRECCION.string' => 'El campo CLIE_DIRECCION debe ser de tipo string',
            'CLIE_DIRECCION.max' => 'El campo CLIE_DIRECCION no debe exceder de 100 caracteres',
            'CLIE_TEL.required' => 'El campo CLIE_TEL es requerido',
            'CLIE_TEL.string' => 'El campo CLIE_TEL debe ser de tipo string',
            'CLIE_TEL.max' => 'El campo CLIE_TEL no debe exceder de 20 caracteres',
            'CLIE_TEL2.required' => 'El campo CLIE_TEL2 es requerido', 
            'CLIE_TEL2.string' => 'El campo CLIE_TEL2 debe ser de tipo string', 
            'CLIE_TEL2.max' => 'El campo CLIE_TEL2 no debe exceder de 20 caracteres',
            'CLIE_MAIL.required' => 'El campo CLIE_MAIL es requerido',  
            'CLIE_MAIL.string' => 'El campo CLIE_MAIL debe ser de tipo string',
            'CLIE_MAIL.max' => 'El campo CLIE_MAIL no debe exceder de 50 caracteres',
            'CLIE_MAIL2.required' => 'El campo CLIE_MAIL2 es requerido',
            'CLIE_MAIL2.string' => 'El campo CLIE_MAIL2 debe ser de tipo string', 
            'CLIE_MAIL2.max' => 'El campo CLIE_MAIL2 no debe exceder de 50 caracteres',
            'CLIE_TIPOCASA.required' => 'El campo CLIE_TIPOCASA es requerido',
            'CLIE_TIPOCASA.string' => 'El campo CLIE_TIPOCASA debe ser de tipo string',

        ];
    }
}
